# -*- coding: utf-8 -*-
"""EvaluacionDiagnostica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15eUY2snmehSdH4bviSl9TRzmGSKwLw2C

Crear lista en python
"""

mi_lista=["a","b","c","d","e"]
print(mi_lista)

"""¿Que funcion se usa para conocer el numero de elementos en una lista?"""

print(len(mi_lista))

"""¿Cual es el resultado de la siguiente expresión?"""

a=[1,2,3,4,5]
print(a[::-1])

"""¿Cual es el resultado de la siguiente expresión?"""

print(3*"5"+2)

"""el error es que no se puede multiplicar por un string

¿Qué salida generará el siguiente código?
"""

def foo(x,y=[]):
  y.append(x)
  return y

print(foo(1))
print(foo(2,[]))
print(foo(3))

"""¿Que resultado obtendremos al ejecutar el siguiente codigo?"""

def multiply_list(numbers,factor):
 result=[]
 for number in numbers:
  result.append(number*factor)
 return result

my_list=[1,2,3]
output=multiply_list(my_list,2)
print(output)